### ISSUE TITLE
how to add new stream urls

### ISSUE THREAD

**Issue by karthikindia** [Kandru/The-Incredible-Radio-Extension#1]
hi 
how to add new stream urls into your API

**Comment by derkalle4** [comment]
Hi,

currently this is a manual process. Feel free to give me the link to the radio. I wanted to work on some automated function but did not have the time to start this yet.

**Comment by karthikindia** [comment]
i am planning to use for only one station
my link is
http://live.nagafm.com:8006/stream.mp3
https://live.nagafm.com:18006/stream.mp3
i am using stunnel to stream with ssl too
both links are there

my idea is to customise like this - https://pix.cobrasoftwares.org/images/2020/03/07/nagafm_chrome.png

please advice

**Comment by derkalle4** [comment]
Hi, feel free to change the script to do this. Simply fork it and change the code behind it. Should not be that problem. I cannot give you helping hands on this because the primary goal of this script is to be able to use many radio stations instead of a single one.

You have to change the popup.html and popup.js to be able to change the layout of the popup to match your screenshot. You also have to change the "tire.js" to be able to only play your radio when clicking on play or stop or pause and remove unnecessary code for getting other radios and the search function. 

This is simple javascript. If you are not familiar with it please get yourself ready with it and how to develop plugins for Chrome: https://developer.chrome.com/extensions/getstarted
